scrapy_settings_dict = {
    'DELAY': 0,
    'BOT_NAME': 'scrape',
    'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3',
    'ROBOTSTXT_OBEY': False,
    'CONCURRENT_REQUESTS': 256,
    'DOWNLOAD_DELAY': 0,
    'CONCURRENT_REQUESTS_PER_DOMAIN': 256,
    'CONCURRENT_REQUESTS_PER_IP': 256,
    'COOKIES_ENABLED': False,
    'TELNETCONSOLE_ENABLED': False,
    'DEFAULT_REQUEST_HEADERS': {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Encoding': 'gzip, deflate',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
    },
    "AUTOTHROTTLE_ENABLED": False,
    "AUTOTHROTTLE_START_DELAY": 2,
    "AUTOTHROTTLE_MAX_DELAY": 60,
    "AUTOTHROTTLE_TARGET_CONCURRENCY": 1.0,
    "AUTOTHROTTLE_DEBUG": False,
    "HTTPCACHE_ENABLED": False,
    "HTTPCACHE_EXPIRATION_SECS": 0,
    "HTTPCACHE_DIR": "httpcache",
    "HTTPCACHE_IGNORE_HTTP_CODES": [],
    "HTTPCACHE_STORAGE": "scrapy.extensions.httpcache.FilesystemCacheStorage",
    "LOG_LEVEL": "INFO",
    "LOG_FILE": "logs/scrapy.log",
    "LOG_FORMAT": "%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    "REDIRECT_ENABLED": True,
    "REDIRECT_MAX_TIMES": 2,
    "DUPEFILTER_DEBUG": False,
    "RETRIES": 3,
    "RETRY_DELAY": 2,
    "RETRY_HTTP_CODES": [500, 502, 503, 504, 408, 403],
    "DOWNLOADER_MIDDLEWARES": {
        "scrapy.downloadermiddlewares.useragent.UserAgentMiddleware": None,
        "scrapy.downloadermiddlewares.retry.RetryMiddleware": None,
    },
}
